package eu.fr.insee.formation.business.entity;
// Generated 25 juin 2017 02:21:10 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment extends AbstractEcolisEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 35991431279109549L;
	private Integer idComment;
	private Utilisateur utilisateur;
	private String corps;
	private Date dateCreation;

	public Comment() {
	}

	public Comment(Utilisateur utilisateur, Date dateCreation) {
		this.utilisateur = utilisateur;
		this.dateCreation = dateCreation;
	}

	public Comment(Utilisateur utilisateur, String corps, Date dateCreation) {
		this.utilisateur = utilisateur;
		this.corps = corps;
		this.dateCreation = dateCreation;
	}

	public Integer getIdComment() {
		return this.idComment;
	}

	public void setIdComment(Integer idComment) {
		this.idComment = idComment;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getCorps() {
		return this.corps;
	}

	public void setCorps(String corps) {
		this.corps = corps;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

}
