package eu.fr.insee.formation.business.entity;
// Generated 25 juin 2017 02:21:10 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Image generated by hbm2java
 */
public class Image extends AbstractEcolisEntity implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6055938211600328115L;
	private Integer idImage;
	private Utilisateur utilisateur;
	private String chemin;
	private Date dateCreation;

	public Image() {
	}

	public Image(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Image(Utilisateur utilisateur, String chemin, Date dateCreation) {
		this.utilisateur = utilisateur;
		this.chemin = chemin;
		this.dateCreation = dateCreation;
	}

	public Integer getIdImage() {
		return this.idImage;
	}

	public void setIdImage(Integer idImage) {
		this.idImage = idImage;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getChemin() {
		return this.chemin;
	}

	public void setChemin(String chemin) {
		this.chemin = chemin;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

}
