package eu.fr.insee.formation.business.entity;
// Generated 25 juin 2017 02:21:10 by Hibernate Tools 5.2.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur extends AbstractEcolisEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8555509805548590121L;
	private Long idUtilisateur;
	private String civilite;
	private String name;
	private String firstname;
	private String login;
	private String password;
	private String email;
	private byte enabled;
	private Date derniereConnexion;
	private int anneeDeNaissance;
	private String telephone;
	private Date dateInscription;
	private List<Annonce> annonces = new ArrayList<Annonce>(0);
	private List<Comment> comments = new ArrayList<Comment>(0);
	private List<Image> images = new ArrayList<Image>(0);

	public Utilisateur() {
	}

	public Utilisateur(String civilite, String email, int anneeDeNaissance,String name,String firstname,String password) {
		this.civilite = civilite;
		this.email = email;
		this.password = password;
		this.anneeDeNaissance = anneeDeNaissance;
		this.name = name;
		this.firstname = firstname;
		this.dateInscription = new Date();
		this.idUtilisateur = System.currentTimeMillis();
		System.out.println(String.format("Identifiant de %s est %d", this.name,this.idUtilisateur));
	}

	public Long getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Long idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	public Date getDerniereConnexion() {
		return this.derniereConnexion;
	}

	public void setDerniereConnexion(Date derniereConnexion) {
		this.derniereConnexion = derniereConnexion;
	}

	public int getAnneeDeNaissance() {
		return this.anneeDeNaissance;
	}

	public void setAnneeDeNaissance(int anneeDeNaissance) {
		this.anneeDeNaissance = anneeDeNaissance;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Date getDateInscription() {
		return this.dateInscription;
	}

	public void setDateInscription(Date dateInscription) {
		this.dateInscription = dateInscription;
	}

	public List<Annonce> getAnnonces() {
		return this.annonces;
	}

	public void setAnnonces(List<Annonce> annonces) {
		this.annonces = annonces;
	}


	public List<Comment> getComments() {
		return this.comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public List<Image> getImages() {
		return this.images;
	}

	public void setImages(List<Image> images) {
		this.images = images;
	}
	
	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
}
